### ISSUE TITLE
[Bug] Handle invalid session

### ISSUE THREAD

**Issue by ahmadgaz** [SJSUCSClub/course-scheduling-server#87]
Currently, this error is thrown if the session is invalid (i.e. the server restarts and the frontend sends outdated cookies). The backend could maybe automatically redirect to login page if this error occurs.   
![Screenshot from 2024-10-21 17-25-09](https://github.com/user-attachments/assets/bdd4fc8d-fb8d-4136-9dc0-fa251b8dbecd)
![image](https://github.com/user-attachments/assets/d18cd22a-1007-46be-895e-d5beeb5d80a8)

**Comment by Jjmaxxx** [comment]
rn returning a 401 error to let the frontend redirect instead
